kind: Namespace
apiVersion: v1
metadata:
  name: reviewer-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewer-ui
  namespace: reviewer-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reviewer-ui
  template:
    metadata:
      labels:
        app: reviewer-ui
        aadpodidbinding: reviewer-ui-label
    spec:
      containers:
      - name: reviewer-ui
        image: ghcr.io/jasoncabot-ms/reviewer/ui:v1.2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: reviewer-ui
  namespace: reviewer-app
  labels:
    app: reviewer-ui
spec:
  type: ClusterIP
  selector:
    app: reviewer-ui
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reviewer-ui
  namespace: reviewer-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - REPLACE_WITH_HOSTNAME.REPLACE_WITH_LOCATION.cloudapp.azure.com
    secretName: reviewer-ui-key
  rules:
  - host: REPLACE_WITH_HOSTNAME.REPLACE_WITH_LOCATION.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reviewer-ui
            port:
              number: 80